import type { StockSheet } from '../stock-sheet';

/**
 * The paper stock sheet for Monday 28 September 2026, the first full stock take, read from the five
 * photographed pages and settled line by line with the owner.
 *
 * Every line on the sheet is here. O.S is `opening`, C.STOCK is `closing`, both in the unit the stock
 * is kept in: bottles and cans, and sticks for cigarettes. A line left blank on the sheet is 0, as the
 * owner asked. What was sold that night is `sales`, at the price on the sheet; the pages' totals come
 * to 6,065, paid 4,655 by M-Pesa (4,555 to the bar's till, 100 to the kitchen's) with 1,410 unpaid.
 *
 * Settled with the owner, over the first reading:
 *  - The 45 on the beers page is Savanna.
 *  - The cans, as the owner read them from the sheet: Tusker Lager 4, Malt 0, Lite 12 (written 10,
 *    corrected to 12), Cider 1, Balozi 10, White Cap 10, Guinness 4, Guinness Smooth 0, Pineapple
 *    Punch 4, Heineken 10, Guarana 13. The sale of one at 300 is the Guinness can, the two at 600 Guarana.
 *  - KC 250ml closed at 36. Three left the shelf and two were paid for (700, the 1,820 page total
 *    corrected to 1,470), so the third is a variance of one, not a sale.
 *  - Soda 300ml: one at 70 and two at 100.
 *  - Bond 7 375ml sells at 850, as it did that night.
 *  - Napoleon is the quarter (250ml): two opened, one sold.
 *  - The Glenfiddich is the 12 year; the whisky bottle is Hamptons drum; one Martell VS, the 750ml.
 *  - "Rosé guavo" and "Gilbey" are tots: Jose Cuervo at 100, and Gilbeys at 100. One Jose Cuervo
 *    bottle is open on the shelf.
 *  - Cigarettes are counted and sold by the stick; Dunhill sticks are 20.
 *  - The unpaid 1,410 is not known to belong to anyone, so it is recorded as unpaid, not as a tab.
 */
export const SHEET_2026_09_28: StockSheet = {
  id: 'sheet-2026-09-28',
  title: 'Stock sheet, Monday 28 September',
  businessDate: '2026-09-28',
  counts: [
    // Beers
    { item: 'Tusker Lager', opening: 38, closing: 33 },
    { item: 'Tusker Malt', opening: 13, closing: 13 },
    { item: 'Tusker Lite', opening: 53, closing: 53 },
    { item: 'Tusker Cider', opening: 15, closing: 15 },
    { item: 'Tusker Ndimu', opening: 0, closing: 0 },
    { item: 'Balozi', opening: 46, closing: 46 },
    { item: 'White Cap', opening: 60, closing: 60 },
    { item: 'White Cap Light', opening: 25, closing: 25 },
    { item: 'Guinness', opening: 23, closing: 21 },
    { item: 'Guinness Smooth', opening: 0, closing: 0 },
    { item: 'Pilsner', opening: 21, closing: 21 },
    { item: 'Pineapple Punch', opening: 34, closing: 34 },
    { item: 'Heineken', opening: 31, closing: 31 },
    { item: 'Heineken Zero', opening: 6, closing: 6 },
    { item: 'Black Ice', opening: 16, closing: 16 },
    { item: 'Desperados', opening: 0, closing: 0 },
    { item: 'Savanna', opening: 45, closing: 45, note: 'The 45 is Savanna, confirmed by the owner.' },
    { item: 'Savanna Lemon', opening: 0, closing: 0 },
    { item: 'Hunters Gold', opening: 14, closing: 14 },
    { item: 'Hunters Dry', opening: 25, closing: 25 },
    { item: 'Raspberry', opening: 26, closing: 26 },
    { item: 'Manyatta', opening: 15, closing: 15 },
    { item: 'Jinro Soju', opening: 9, closing: 9 },
    { item: 'KO', opening: 20, closing: 20 },
    { item: 'Summit', opening: 0, closing: 0 },
    // Cans, read one row lower than first read: see above.
    { item: 'Tusker Lager can', opening: 4, closing: 4 },
    { item: 'Tusker Malt can', opening: 0, closing: 0 },
    { item: 'Tusker Lite can', opening: 12, closing: 12, note: 'Written 10, corrected to 12.' },
    { item: 'Tusker Cider can', opening: 1, closing: 1 },
    { item: 'Balozi can', opening: 10, closing: 10 },
    { item: 'White Cap can', opening: 10, closing: 10 },
    { item: 'Guinness can', opening: 4, closing: 3 },
    { item: 'Guinness Smooth can', opening: 0, closing: 0 },
    { item: 'Pineapple Punch can', opening: 4, closing: 4 },
    { item: 'Heineken can', opening: 10, closing: 10 },
    { item: 'Guarana can', opening: 13, closing: 11 },
    { item: 'Black Ice can', opening: 13, closing: 13 },
    { item: 'Raspberry can', opening: 12, closing: 12 },
    { item: 'Manyatta can', opening: 6, closing: 6 },
    { item: 'Snapp can', opening: 17, closing: 17 },
    { item: 'Red Bull can', opening: 4, closing: 4 },
    { item: "Gordon's Dry can", opening: 18, closing: 18 },
    { item: "Gordon's Pink can", opening: 5, closing: 4 },
    { item: 'Faxe can', opening: 2, closing: 2 },
    // Soft drinks
    { item: 'Soda 300ml', opening: 44, closing: 41 },
    { item: 'Soda 500ml bottle', opening: 38, closing: 37 },
    { item: 'Soda 500ml plastic', opening: 0, closing: 0 },
    { item: 'Soda 1 litre plastic', opening: 6, closing: 6 },
    { item: 'Soda 1.25 litres', opening: 0, closing: 0 },
    { item: 'Dasani 1 litre', opening: 21, closing: 21 },
    { item: 'Dasani 500ml', opening: 12, closing: 12 },
    { item: 'Minute Maid 1 litre', opening: 9, closing: 9 },
    { item: 'Minute Maid 500ml', opening: 9, closing: 9 },
    { item: 'Monster', opening: 6, closing: 6 },
    { item: 'Charged', opening: 3, closing: 3 },
    { item: 'Sweepers', opening: 0, closing: 0 },
    { item: 'Predator', opening: 1, closing: 1 },
    { item: 'Tonic', opening: 22, closing: 22 },
    { item: 'Del Monte', opening: 0, closing: 0 },
    { item: 'Lemonade', opening: 5, closing: 5, note: 'Written 4, corrected to 5, on the Lemonade row.' },
    { item: 'Pepsi', opening: 0, closing: 0 },
    { item: '7 Up', opening: 0, closing: 0 },
    { item: 'Mountain Dew', opening: 0, closing: 0 },
    { item: 'Lime juice', opening: 0, closing: 0 },
    { item: 'Water 1 litre', opening: 18, closing: 17 },
    { item: 'Water 500ml', opening: 225, closing: 225 },
    // Spirits
    { item: 'KC 250ml', opening: 39, closing: 36, note: 'Three left the shelf, two were paid for.' },
    { item: 'KC 375ml', opening: 0, closing: 0 },
    { item: 'KC 750ml', opening: 6, closing: 6 },
    { item: 'Chrome 250ml', opening: 16, closing: 16 },
    { item: 'Chrome 750ml', opening: 3, closing: 3 },
    { item: 'Captain Morgan 250ml', opening: 1, closing: 1 },
    { item: 'Captain Morgan 750ml', opening: 3, closing: 3 },
    { item: 'County 250ml', opening: 0, closing: 0 },
    { item: 'County 750ml', opening: 4, closing: 4 },
    { item: 'Hunters Choice 250ml', opening: 3, closing: 3 },
    { item: 'Hunters Choice 750ml', opening: 4, closing: 4 },
    { item: 'Gilbeys 250ml', opening: 2, closing: 2 },
    { item: 'Gilbeys 375ml', opening: 2, closing: 2 },
    { item: 'Gilbeys 750ml', opening: 2, closing: 2 },
    { item: 'Richot 250ml', opening: 0, closing: 0 },
    { item: 'Richot 375ml', opening: 0, closing: 0 },
    { item: 'Richot 750ml', opening: 1, closing: 1 },
    { item: 'Viceroy 250ml', opening: 3, closing: 3 },
    { item: 'Viceroy 375ml', opening: 0, closing: 0 },
    { item: 'Viceroy 750ml', opening: 2, closing: 2 },
    { item: 'Smirnoff 250ml', opening: 3, closing: 3 },
    { item: 'Smirnoff 375ml', opening: 0, closing: 0 },
    { item: 'Smirnoff 750ml', opening: 1, closing: 1 },
    { item: 'Kibao 250ml', opening: 4, closing: 4 },
    { item: 'Kibao 375ml', opening: 1, closing: 1 },
    { item: 'Kibao 750ml', opening: 3, closing: 3 },
    { item: 'Napoleon', opening: 2, closing: 1, note: 'The quarter, 250ml.' },
    { item: 'Kane Extra 250ml', opening: 0, closing: 0 },
    { item: 'Kane Extra 750ml', opening: 0, closing: 0 },
    { item: 'Cosmo Smirnoff', opening: 1, closing: 1 },
    { item: 'Cosmo Gilbeys', opening: 1, closing: 1 },
    { item: 'Cosmo Captain', opening: 1, closing: 1 },
    { item: 'Konyagi 250ml', opening: 0, closing: 0 },
    { item: 'Konyagi 375ml', opening: 1, closing: 1 },
    { item: "Gordon's 375ml", opening: 2, closing: 2 },
    { item: "Gordon's 750ml", opening: 2, closing: 2 },
    { item: 'VAT 69 375ml', opening: 1, closing: 1 },
    { item: 'VAT 69 750ml', opening: 1, closing: 1 },
    { item: 'Bond 7 250ml', opening: 2, closing: 2 },
    { item: 'Bond 7 375ml', opening: 2, closing: 1 },
    { item: 'Bond 7 750ml', opening: 2, closing: 2 },
    { item: "Jack Daniel's 375ml", opening: 0, closing: 0 },
    { item: "Jack Daniel's 750ml", opening: 1, closing: 1 },
    { item: "Jack Daniel's 1 litre", opening: 0, closing: 0 },
    { item: 'Red Label 375ml', opening: 2, closing: 2 },
    { item: 'Red Label 750ml', opening: 1, closing: 1 },
    { item: 'Red Label 1 litre', opening: 0, closing: 0 },
    { item: 'Black Label 375ml', opening: 1, closing: 1 },
    { item: 'Black Label 750ml', opening: 0, closing: 0 },
    { item: 'Black Label 1 litre', opening: 2, closing: 2 },
    { item: 'Double Black 750ml', opening: 0, closing: 0 },
    { item: 'Double Black 1 litre', opening: 2, closing: 2 },
    { item: 'Grants 750ml', opening: 2, closing: 2 },
    { item: 'Camino 750ml', opening: 1, closing: 1 },
    { item: 'Camino T 750ml', opening: 0, closing: 0 },
    { item: 'Jameson 750ml', opening: 1, closing: 1 },
    { item: 'Jameson 1 litre', opening: 0, closing: 0 },
    { item: 'Best Whisky 750ml', opening: 0, closing: 0 },
    { item: 'Best Cream 750ml', opening: 0, closing: 0 },
    { item: 'John Barr 750ml', opening: 0, closing: 0 },
    { item: 'John Barr 1 litre', opening: 0, closing: 0 },
    { item: 'Glenfiddich 12', opening: 1, closing: 1 },
    { item: 'Glenfiddich 15', opening: 0, closing: 0 },
    { item: 'Glenfiddich 18', opening: 0, closing: 0 },
    { item: 'Chivas 750ml', opening: 0, closing: 0 },
    { item: "Ballantine's 750ml", opening: 1, closing: 1 },
    { item: 'Famous Grouse 1 litre', opening: 1, closing: 1 },
    { item: 'Southern Comfort', opening: 0, closing: 0 },
    { item: 'Hamptons drum', opening: 1, closing: 1 },
    { item: 'Black & White', opening: 0, closing: 0 },
    { item: 'Amarula', opening: 0, closing: 0 },
    { item: 'Singleton 12', opening: 0, closing: 0 },
    { item: 'Singleton 15', opening: 0, closing: 0 },
    { item: 'Baileys', opening: 0, closing: 0 },
    { item: 'Jagermeister', opening: 0, closing: 0 },
    { item: 'Royal Circle', opening: 0, closing: 0 },
    { item: 'Hennessy VS', opening: 0, closing: 0 },
    { item: 'Hennessy VSOP', opening: 0, closing: 0 },
    { item: 'Martell VS 750ml', opening: 1, closing: 1 },
    { item: 'Martell VS 1 litre', opening: 0, closing: 0 },
    { item: 'Martell VSOP 750ml', opening: 0, closing: 0 },
    { item: 'Martell VSOP 1 litre', opening: 0, closing: 0 },
    { item: 'Remy Martin (11,500)', opening: 0, closing: 0 },
    { item: 'Remy Martin (15,000)', opening: 0, closing: 0 },
    { item: 'Jose Cuervo 750ml', opening: 1, closing: 1, note: 'Written in as "Rosé guavo": one bottle open, one tot sold.' },
    { item: 'Jose Cuervo Gold 750ml', opening: 0, closing: 0 },
    // Wines
    { item: 'Caprice Red 1 litre', opening: 2, closing: 2 },
    { item: 'Caprice White 1 litre', opening: 1, closing: 1 },
    { item: 'Casabuena', opening: 1, closing: 1 },
    { item: '4th Street Red Sweet 1 litre', opening: 0, closing: 0 },
    { item: '4th Street White Sweet 1 litre', opening: 0, closing: 0 },
    { item: 'Drostdy-Hof Red 750ml', opening: 1, closing: 1 },
    { item: 'Nederburg 750ml', opening: 1, closing: 1 },
    { item: 'Robertson Red 750ml', opening: 0, closing: 0 },
    { item: '4th Street White 750ml', opening: 0, closing: 0 },
    { item: '4th Street Red 750ml', opening: 0, closing: 0 },
    { item: 'Four Cousins Red 750ml', opening: 0, closing: 0 },
    { item: 'Four Cousins White 750ml', opening: 1, closing: 1 },
    { item: 'Rosso Nobile', opening: 0, closing: 0 },
    { item: 'Asconi', opening: 0, closing: 0 },
    { item: 'Kiss Me', opening: 0, closing: 0 },
    { item: 'Black Bird', opening: 0, closing: 0 },
    { item: 'Cellar Cask', opening: 0, closing: 0 },
    { item: 'Bianco Nobile', opening: 0, closing: 0 },
    // Cigarettes, in sticks
    { item: 'Dunhill Embassy B', opening: 0, closing: 0 },
    { item: 'Dunhill Embassy W', opening: 0, closing: 0 },
    { item: 'Dunhill Single', opening: 0, closing: 0 },
    { item: 'Dunhill Double', opening: 17, closing: 17 },
    { item: 'Pall Mall Red', opening: 92, closing: 84 },
    { item: 'Pall Mall Green S', opening: 40, closing: 40 },
    { item: 'Pall Mall Blue S', opening: 41, closing: 40 },
    { item: 'Rothmans', opening: 27, closing: 5, note: 'Written as Rothmans, Sportsman.' },
    { item: 'Embassy', opening: 20, closing: 20 },
  ],
  sales: [
    { item: 'Tusker Lager', qty: 5, price: 250 },
    { item: 'Guinness', qty: 2, price: 280 },
    { item: 'Guinness can', qty: 1, price: 300 },
    { item: 'Guarana can', qty: 2, price: 300 },
    { item: "Gordon's Pink can", qty: 1, price: 300 },
    { item: 'Soda 300ml', qty: 1, price: 70 },
    { item: 'Soda 300ml', qty: 2, price: 100 },
    { item: 'Soda 500ml bottle', qty: 1, price: 100 },
    { item: 'Water 1 litre', qty: 1, price: 100 },
    { item: 'KC 250ml', qty: 2, price: 350 },
    { item: 'Bond 7 375ml', qty: 1, price: 850 },
    { item: 'Napoleon', qty: 1, price: 300 },
    { item: 'Jose Cuervo 750ml', way: 'tot', qty: 1, price: 100 },
    { item: 'Gilbeys 750ml', way: 'tot', qty: 1, price: 100 },
    { item: 'Pall Mall Red', way: 'stick', qty: 8, price: 10 },
    { item: 'Pall Mall Blue S', way: 'stick', qty: 1, price: 15 },
    { item: 'Rothmans', way: 'stick', qty: 22, price: 20 },
  ],
  tenders: [
    { kind: 'mpesa', amount: 4655, reference: 'From the stock sheet: 4,555 to the bar till, 100 to the kitchen till' },
    { kind: 'account', amount: 1410, reference: 'Unpaid on the stock sheet' },
  ],
  menu: {
    // A tot is 25ml, poured from the bottle the stock is kept in: 30 to a 750ml bottle, 40 to a litre.
    totMl: 25,
    tots: [
      { item: 'Double Black 1 litre', price: 400 },
      { item: "Jack Daniel's 750ml", price: 250 },
      { item: 'Black Label 1 litre', price: 250 },
      { item: 'Amarula', price: 300, bottleMl: 750 },
      { item: 'Jagermeister', price: 200, bottleMl: 700 },
      { item: 'Gilbeys 750ml', price: 100 },
      { item: 'Jose Cuervo 750ml', price: 100 },
      { item: 'Jose Cuervo Gold 750ml', price: 150 },
      { item: 'Best Whisky 750ml', price: 100 },
      { item: 'Viceroy 750ml', price: 150 },
    ],
    // Tequila poured by the tot and kept as bottles. The bottle is not yet priced for sale whole.
    newProducts: [
      { name: 'Jose Cuervo 750ml', category: 'Spirits', bottleMl: 750 },
      { name: 'Jose Cuervo Gold 750ml', category: 'Spirits', bottleMl: 750 },
    ],
    // Counted and sold by the stick; a pack of 20 takes 20 sticks.
    sticks: [
      { item: 'Dunhill Embassy B', stick: 20, pack: 600 },
      { item: 'Dunhill Embassy W', stick: 20, pack: 600 },
      { item: 'Dunhill Single', stick: 20, pack: 600 },
      { item: 'Dunhill Double', stick: 20, pack: 600 },
      { item: 'Pall Mall Red', stick: 10, pack: 200 },
      { item: 'Pall Mall Green S', stick: 15, pack: 300 },
      { item: 'Pall Mall Blue S', stick: 15, pack: 300 },
      { item: 'Rothmans', stick: 20, pack: 400 },
      { item: 'Embassy', stick: 30, pack: 600 },
    ],
    prices: [{ item: 'Bond 7 375ml', price: 850 }],
  },
};
