/**
 * Generates packages/ui/src/styles/tokens.css from packages/ui/src/tokens/tokens.ts.
 *
 *   pnpm tokens:build   write the file
 *   pnpm tokens:check   fail if the file is out of date (CI)
 *
 * The Tailwind theme is reset first, so utilities that are not tokens do not exist: no default
 * palette, no bold, no pills, no spacing values outside the scale.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { atmosphere, breakpoints, colour, elevation, fontFamily, motion, radius, size, space, themes, type, weight } from '../packages/ui/src/tokens/tokens';

const OUT = resolve(import.meta.dirname, '../packages/ui/src/styles/tokens.css');

const px = (n: number) => `${n}px`;
const lines: string[] = [];
const push = (s = '') => lines.push(s);

push('/*');
push(' * Generated by scripts/build-tokens.ts from packages/ui/src/tokens/tokens.ts.');
push(' * Do not edit by hand. Run `pnpm tokens:build`.');
push(' */');
push();
push('@theme {');
for (const ns of [
  'color',
  'font',
  'text',
  'font-weight',
  'tracking',
  'leading',
  'radius',
  'shadow',
  'inset-shadow',
  'drop-shadow',
  'text-shadow',
  'blur',
  'ease',
  'animate',
  'breakpoint',
  'perspective',
  'aspect',
]) {
  push(`  --${ns}-*: initial;`);
}
push('  --spacing: initial;');
push();
push(`  --font-sans: ${fontFamily.sans};`);
push(`  --font-mono: ${fontFamily.mono};`);
push(`  --font-weight-regular: ${weight.regular};`);
push(`  --font-weight-medium: ${weight.medium};`);
push();
for (const [name, t] of Object.entries(type)) {
  push(`  --text-${name}: ${px(t.size)};`);
  push(`  --text-${name}--line-height: ${px(t.lineHeight)};`);
  push(`  --text-${name}--letter-spacing: ${t.tracking};`);
  push(`  --text-${name}--font-weight: ${t.weight};`);
}
push();
push('  --spacing-0: 0px;');
push('  --spacing-px: 1px;');
for (const n of space) push(`  --spacing-${n}: ${px(n)};`);
for (const [name, value] of Object.entries(size)) push(`  --spacing-${name}: ${px(value)};`);
push();
for (const [name, value] of Object.entries(radius)) push(`  --radius-${name}: ${px(value)};`);
push();
push(`  --ease-out: ${motion.ease.out};`);
push(`  --ease-in: ${motion.ease.in};`);
push(`  --ease-in-out: ${motion.ease.inOut};`);
push(`  --ease-snap: ${motion.ease.snap};`);
push();
for (const [name, value] of Object.entries(breakpoints)) push(`  --breakpoint-${name}: ${value / 16}rem;`);
push();
for (const [name, value] of Object.entries(atmosphere.blur)) push(`  --blur-${name}: ${px(value)};`);
push('  --animate-breathe: bliss-breathe 1600ms cubic-bezier(0.65, 0, 0.35, 1) infinite;');
push();
colour.seat.forEach((hex, i) => push(`  --color-seat-${i + 1}: ${hex};`));
push(`  --color-seat-ink: ${colour.seatText};`);
push('}');
push();
push('@theme inline {');
for (const name of Object.keys(themes.dark)) push(`  --color-${name}: var(--bliss-${name});`);
push('  --color-scrim: var(--bliss-scrim);');
  for (const name of Object.keys(elevation)) push(`  --shadow-${name}: var(--bliss-shadow-${name});`);
  push('  --shadow-lift: var(--bliss-shadow-lift);');
  push('  --shadow-key: var(--bliss-shadow-key);');
  push('}');
push();

function themeBlock(selector: string, name: keyof typeof themes, scheme: 'light' | 'dark') {
  push(`${selector} {`);
  push(`  color-scheme: ${scheme};`);
  for (const [key, value] of Object.entries(themes[name])) push(`  --bliss-${key}: ${value};`);
  push(`  --bliss-scrim: ${colour.scrim};`);
  for (const [elevName, elevVal] of Object.entries(elevation)) {
    push(`  --bliss-shadow-${elevName}: ${elevVal[name]};`);
  }
  push(`  --bliss-shadow-lift: ${atmosphere.lift[name]};`);
  push(`  --bliss-shadow-key: ${atmosphere.key[name]};`);
  push('}');
  push();
}

themeBlock(":root,\n[data-theme='light']", 'light', 'light');
themeBlock("[data-theme='dark']", 'dark', 'dark');

push(':root {');
push(`  --bliss-duration-hover: ${motion.hoverMs}ms;`);
push(`  --bliss-duration-press: ${motion.pressMs}ms;`);
push(`  --bliss-ease-out: ${motion.ease.out};`);
push(`  --bliss-ease-snap: ${motion.ease.snap};`);
push(`  --bliss-duration-surface: ${atmosphere.surfaceMs}ms;`);
push(`  --bliss-duration-glide: ${atmosphere.glideMs}ms;`);
push(`  --bliss-scale-press: ${atmosphere.pressScale};`);
push(`  --bliss-scale-key: ${atmosphere.keyScale};`);
push('}');

const output = `${lines.join('\n')}\n`;

if (process.argv.includes('--check')) {
  let current = '';
  try {
    current = readFileSync(OUT, 'utf8');
  } catch {
    current = '';
  }
  if (current.replace(/\r\n/g, '\n') !== output) {
    console.error('packages/ui/src/styles/tokens.css is out of date. Run `pnpm tokens:build`.');
    process.exit(1);
  }
  console.log('tokens.css is up to date.');
} else {
  writeFileSync(OUT, output);
  console.log(`Wrote ${OUT}`);
}
